# Data kecamatan
kecamatan = {
    'Asemrowo': {'neighbors': {'Benowo': 8, 'Tandes': 3, 'Sukomanunggal': 2, 'Bubutan': 4, 'Krembangan': 5}, 'coordinates': (11, 14)},
    'Benowo': {'neighbors': {'Pakal': 5, 'Sambikerep': 5, 'Tandes': 3, 'Asemrowo': 8}, 'coordinates': (7, 15)},
    'Bubutan': {'neighbors': {'Krembangan': 5, 'Asemrowo': 4, 'Sawahan': 5, 'Genteng': 3}, 'coordinates': (15, 13)},
    'Bulak': {'neighbors': {'Kenjeran': 5, 'Tambaksari': 5, 'Mulyorejo': 5}, 'coordinates': (22, 15)},
    'Dukuh Pakis': {'neighbors': {'Sukomanunggal': 2, 'Wiyung': 5, 'Jambangan': 10, 'Wonokromo': 8, 'Sawahan': 6}, 'coordinates': (13, 8)},
    'Gayungan': {'neighbors': {'Jambangan': 1, 'Wonocolo': 5, 'Wonokromo': 5}, 'coordinates': (15, 3)},
    'Genteng': {'neighbors': {'Pabean Cantikan': 7, 'Bubutan': 3, 'Sawahan': 7, 'Tegalsari': 5, 'Gubeng': 3, 'Tambaksari': 3, 'Simokerto': 3,}, 'coordinates': (7, 12)},
    'Gubeng': {'neighbors': {'Tambaksari': 5, 'Genteng': 3, 'Tegalsari': 3, 'Wonokromo': 5, 'Sukolilo': 5, 'Mulyorejo': 5}, 'coordinates': (19, 10)},
    'Gununganyar': {'neighbors': {'Rungkut': 4, 'Tenggilis Mejoyo': 6}, 'coordinates': (22, 3)},
    'Jambangan': {'neighbors': {'Dukuh Pakis': 10, 'Wiyung': 6, 'Karangpilang': 6, 'Gayungan': 1, 'Wonokromo': 6}, 'coordinates': (14, 5)},
    'Karang Pilang': {'neighbors': {'Wiyung': 5, 'Lakarsantri': 8, 'Jambangan': 5}, 'coordinates': (11, 3)},
    'Kenjeran': {'neighbors': {'Semampir': 3, 'Simokerto': 5, 'Tambaksari': 5, 'Bulak': 5,}, 'coordinates': (20, 16)},
    'Krembangan': {'neighbors': {'Asemrowo': 5, 'Bubutan': 5, 'Pabean Cantikan': 3}, 'coordinates': (15, 16)},
    'Lakarsantri': {'neighbors': {'Sambikerep': 5, 'Wiyung': 3, 'Karangpilang': 8,}, 'coordinates': (8, 6)},
    'Mulyorejo': {'neighbors': {'Bulak': 5, 'Tambaksari': 4, 'Gubeng': 5, 'Sukolilo': 4}, 'coordinates': (23, 11)},
    'Pabean Cantikan': {'neighbors': {'Krembangan': 3, 'Genteng': 7, 'Simokerto': 5, 'Semampir': 4}, 'coordinates': (16, 16)},
    'Pakal': {'neighbors': {'Benowo': 5}, 'coordinates': (3, 16)},
    'Rungkut': {'neighbors': {'Sukolilo': 3, 'Tenggilis Mejoyo': 6, 'Gununganyar': 4}, 'coordinates': (22, 5)},
    'Sambikerep': {'neighbors': {'Benowo': 5, 'Lakarsantri': 5, 'Wiyung': 8, 'Sukomanunggal': 7, 'Tandes': 3}, 'coordinates': (7, 10)},
    'Sawahan': {'neighbors': {'Bubutan': 5, 'Sukomanunggal': 4, 'Dukuh Pakis': 6, 'Wonokromo': 5, 'Tegalsari': 2, 'Genteng': 7}, 'coordinates': (15, 11)},
    'Semampir': {'neighbors': {'Pabean Cantikan': 4, 'Simokerto': 5, 'Kenjeran': 3,}, 'coordinates': (17, 17)},
    'Simokerto': {'neighbors': {'Semampir': 5, 'Pabean Cantikan': 5, 'Genteng': 3, 'Tambaksari': 3, 'Kenjeran': 5}, 'coordinates': (18, 15)},
    'Sukolilo': {'neighbors': {'Mulyorejo': 4, 'Gubeng': 5, 'Rungkut': 3, 'Tenggilis Mejoyo': 5}, 'coordinates': (23, 8)},
    'Sukomanunggal': {'neighbors': {'Asemrowo': 2, 'Tandes': 4, 'Sambikerep': 7, 'Dukuh Pakis': 2, 'Sawahan': 4,}, 'coordinates': (12, 11)},
    'Tambaksari': {'neighbors': {'Kenjeran': 5, 'Simokerto': 3, 'Genteng': 3, 'Gubeng': 5, 'Mulyorejo': 4, 'Bulak': 5}, 'coordinates': (20, 13)},
    'Tandes': {'neighbors': {'Asemrowo': 3, 'Benowo': 3, 'Sambikerep': 3, 'Sukomanunggal': 4}, 'coordinates': (9, 13)},
    'Tegalsari': {'neighbors': {'Genteng': 5, 'Sawahan': 2, 'Gubeng': 3, 'Wonokromo': 4}, 'coordinates': (16, 10)},
    'Tenggilis Mejoyo': {'neighbors': {'Wonocolo': 3, 'Sukolilo': 5, 'Gununganyar': 6, 'Rungkut': 6}, 'coordinates': (18, 4)},
    'Wiyung': {'neighbors': {'Dukuh Pakis': 5, 'Jambangan': 6, 'Karang Pilang': 5, 'Lakarsantri': 3, 'Sambikerep': 8}, 'coordinates': (11, 6)},
    'Wonocolo': {'neighbors': {'Wonokromo': 2, 'Gayungan': 5, 'Tenggilis Mejoyo': 3}, 'coordinates': (17, 5)},
    'Wonokromo': {'neighbors': {'Dukuh Pakis': 8, 'Gayungan': 5, 'Gubeng': 5, 'Sawahan': 5, 'Tegalsari': 4, 'Wonocolo': 2, 'Jambangan': 6}, 'coordinates': (16, 7)}
}